name: pluton-server-dev
services:
  db:
    image: postgres:18.0-alpine3.22
    environment:
      - POSTGRES_DB=pluton_db_dev
      - POSTGRES_USER=devuser
      - POSTGRES_PASSWORD=devpassword
    ports:
      - "5432:5432"
  keycloak:
    image: quay.io/keycloak/keycloak:26.4.2-0
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
    command:
      - start-dev
      - --db=dev-file
    ports:
      - "9090:8080"
    volumes:
      - keycloak-data:/opt/keycloak/data

volumes:
  keycloak-data:
    driver: local