# Database
spring.datasource.url=jdbc:postgresql://localhost:5432/pluton_db_dev
spring.datasource.username=devuser
spring.datasource.password=devpassword

spring.jpa.hibernate.ddl-auto=create-drop

jwt.secret=0bfbbc0538b1fa13c3803bcf55d72754dcb90e9fb55005c9fa097a5b7f32a362
jwt.expiration=360000