spring.application.name=Pluton Server
spring.jpa.open-in-view=false
server.port=8080
spring.profiles.active=dev

# Logging
logging.level.org.springframework.security=TRACE

management.endpoint.health.show-components=always
management.endpoint.health.probes.enabled=true

# Spring Security
spring.security.oauth2.resourceserver.jwt.issuer-uri=http://localhost:8080

spring.security.oauth2.client.registration.google.client-id=${GOOGLE_CLIENT_ID}
spring.security.oauth2.client.registration.google.client-secret=${GOOGLE_CLIENT_SECRET}

spring.security.oauth2.client.registration.github.client-id=${GITHUB_CLIENT_ID}
spring.security.oauth2.client.registration.github.client-secret=${GITHUB_CLIENT_SECRET}

# Pluton Security
security.password.min-length=15
security.password.require-uppercase=false
security.password.require-lowercase=false
security.password.require-digit=false
security.password.require-special=false

security.jwt.secret=${JWT_SECRET}

# Mail
spring.mail.host=smtp.purelymail.com
spring.mail.port=587
spring.mail.username=${PLUTON_EMAIL}
spring.mail.password=${PLUTON_EMAIL_APP_PASSWORD}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true