# Datasource
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}

# RSA Keys
rsa.private-key=${RSA_PRIVATE_KEY_PATH}
rsa.public-key=${RSA_PUBLIC_KEY_PATH}