# General
logging.level.org.springframework.security=DEBUG

# Datasource
spring.datasource.url=jdbc:postgresql://localhost:5432/pluton
spring.datasource.username=test
spring.datasource.password=password

# RSA Keys
rsa.private-key=classpath:certs/private.pem
rsa.public-key=classpath:certs/public.pem

# Flyway
spring.flyway.clean-disabled=false