# General
logging.level.org.springframework.security=DEBUG

# Datasource
spring.datasource.url=jdbc:postgresql://localhost:5432/pluton
spring.datasource.username=test
spring.datasource.password=password

# RSA Keys
pluton.rsa.private-key=classpath:certs/private.pem
pluton.rsa.public-key=classpath:certs/public.pem

# Flyway
spring.flyway.clean-disabled=false

# Email
spring.mail.host=localhost
spring.mail.port=1025
spring.mail.properties.mail.smtp.auth=false
spring.mail.properties.mail.smtp.starttls.enable=false
pluton.mail.from-address=dev@pluton.local